apiVersion: v1
kind: Service
metadata:
  name: metrics-queue-nodeport
  labels:
    app: metrics-queue
spec:
  type: NodePort
  selector:
    app: metrics-queue
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30000
